version: '3.1'

services:

  wordpress:
    image: wordpress:5.3.2-php7.4
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
      - ./docker/wordpress/upload.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
  db:
    image: mysql:5.7.20
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./db:/var/lib/mysql

volumes:
  wordpress:
  db:
